---
output: pdf_document
header-includes:
- \usepackage{graphicx,latexsym}
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{longtable,booktabs,setspace, dsfont}
---

<!--
You can delete the header-includes (lines 3-6 above) if you like and also the chunk below since it is loaded in the skeleton.Rmd file.  They are included so that chap3.Rmd will compile by itself when you hit Knit PDF.
-->

```{r include_reedtemplates_4, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```


# Model 1: Rides and Riders

We start out model simply and then building up. First, we describe a logistic
regression model to use as our baseline from which we compare our multilevel
logstic regression models. Then we describe models that account for variance in
rider rating patterns with varying intercepts and varying slopes. Finally, we
compare the models.

## Baseline Model: Just Ride-Level Parameters

As a starting point, we can create a straight forward logistic regression model,
where we predict ride rating based on ride level predictors. 

There is a selection of variables to choose from as predictors:

- length
- weather
    * rainfall in last hour
    * rainfall in past four hours
    * windspeed
    * gust speed
- time of day

$$
\mathbb{P} (y_i = 1) = \text{logit}^{-1} \left(
\alpha + \beta_1 \cdot x^\text{log.length}_i + \beta_2 \cdot x^\text{log.wind.speed}_i +
\beta_3 \cdot x^\text{log.rainfall.4h}_i
\right).
$$


### Weather


### Traffic

We would like to have some model for the effect of traffic. We don't have actual
traffic data, but we do know that there are fluxuations in how riders rate rides
based on time of day, with somewhat higher rates during the morning and evening.
The simplist way to model this might be a rush hour indicator:

\[ x_i^{\text{rush.hour}} = 
\mathds{1} [x_i^{\text{time}} \text{during rush hour}],
\]

where rush hour is defined as between 7 a.m. and 9 a.m. and 5 p.m. and 7 p.m.
on weekdays. However this maybe a little too naive. We might also want to simply
have a term that absorbed all time of day difference in ratings.

We might consider adding a term that is a sinusoidal function with a period of
one day. We would be interested in fitting a term,

$$A \sin (T x^{\text{time}} + \phi),$$

where $\beta$ and $\phi$ are coefficients estimated and $T = 2 \pi / d,$ where
$d$ is the period of one day ($8.64 \times 10^7$ milliseconds.) This form isn't
easy to estimate, but we can transform this expression into the sum of two
trignometric functions:

\begin{align*}
A \sin (T x + \phi) &= 
A \left( \sin (T x) \cos (\phi) + \cos (T x) \sin (\phi) \right)\\
&= (A + \cos (\phi)) \sin (T x) + \sin (\phi) \cos (T x)\\
&= \beta_1 \sin (T x) + \beta_2 \cos (T x),
\end{align*}

where $\beta_1 = A + \cos (\phi)$ and $\beta_2 = \sin (\phi).$ This term won't
model just traffic; it will probably absorb all effects that are cyclical over
the day. 

## Adding Random Effects from Riders {#add-riders}

## Evaluating the Ride-Level Models
