---
output: pdf_document
header-includes:
- \usepackage{graphicx,latexsym}
- \usepackage{amssymb,amsthm,amsmath}
- \usepackage{longtable,booktabs,setspace}
---

<!--
You can delete the header-includes (lines 3-6 above) if you like and also the chunk below since it is loaded in the skeleton.Rmd file.  They are included so that chap3.Rmd will compile by itself when you hit Knit PDF.
-->

```{r include_reedtemplates_6, include = FALSE}
# This chunk ensures that the reedtemplates package is installed and loaded
# This reedtemplates package includes the template files for the thesis and also
# two functions used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")

if(!require(reedtemplates)){
  library(devtools)
  devtools::install_github("ismayc/reedtemplates")
  }
library(reedtemplates)
```


# Classifying Riders

We don't expect riders to be the same. In fact, we saw this with our models in 
Chapter 3: the rider intercepts encoded a lot of information about the typical
time of day a rider tends to ride. In this chapter we try to get a picture of 
how these patterns in rider behavior vary between riders, and then determine
if this gives useful information to our model as group-level predictors.

## Characterizing Rider Length and Time Patterns

Sometime we would like to give a summary of patterns we see in data. Sometimes
statistical summaries like the mean or median are useful. But take the example
of the times of day a rider goes on bicycle rides. Is the mean or median time
useful at all? Not really. 

A good description of a riders time of day patterns might be the proportion of
their rides fall within each our of the day. This gives us a sort of distribution
for their riders time of day. The question we can answer from there is: Can these
patterns be described with good accuracy with a lower dimensional vector?

Define the number of rides in hour $h \in \{0, \ldots, 23\}$ for rider $j$ as

$$n(h,j) = \left|\left\{i \: | \: X^\text{rider}_i = j,
\lfloor X^\text{time}_i \rfloor = h \right\}\right|$$

(Recall that $X^\text{time} \in [0, 24)^n$, i.e it is measured in hours since
midnight.)

We can then define the rider time of day matrix as $P$, where

$$P_{ij} = \frac{n(i,j)}{\sum_{h = 0}^{23} n(h,j) }.$$

Now we can ask, what are the principal components of these column vectors?

## Models with Rider-level predictors

